# Generated by Django 5.0.1 on 2024-02-13 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usluga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to='uslugi')),
                ('type', models.CharField(max_length=50)),
                ('place_ammount', models.CharField(max_length=50)),
                ('rent_ammount', models.CharField(max_length=50)),
                ('pay_type', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
