# Generated by Django 5.0.1 on 2024-02-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.DurationField()),
                ('cover_image', models.ImageField(upload_to='covers/')),
                ('record_type', models.CharField(max_length=10)),
                ('payment_type', models.CharField(max_length=20)),
            ],
        ),
    ]
