# Generated by Django 5.0.1 on 2024-02-13 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_usluga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usluga',
            name='avatar',
        ),
    ]
