# Generated by Django 5.0.1 on 2024-02-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_usluga_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usluga',
            name='serviceCover',
            field=models.ImageField(blank=True, null=True, upload_to='service_covers/'),
        ),
    ]
