# Generated by Django 5.0.1 on 2024-02-02 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_service_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='cover_image',
            new_name='cover',
        ),
    ]
