# Generated by Django 5.0.1 on 2024-02-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_usluga_servicecover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usluga',
            name='serviceCover',
            field=models.ImageField(upload_to='service_covers/'),
        ),
    ]
