# Generated by Django 5.0.1 on 2024-02-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_reset_passwrod'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/default_avatar.svg', upload_to='avatars/'),
        ),
    ]
