# Generated by Django 5.0.1 on 2024-02-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('secondname', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='employees/')),
                ('serviceid', models.IntegerField()),
                ('worktime', models.CharField(max_length=20)),
                ('timetable', models.CharField(max_length=10)),
                ('chilltime', models.CharField(max_length=20)),
            ],
        ),
    ]
