# Generated by Django 5.0.2 on 2024-02-25 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_buisness_sphere'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='type',
        ),
        migrations.AddField(
            model_name='branch',
            name='active_days',
            field=models.CharField(default='Пн', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.CharField(default='sovetskaya 13b', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='business',
            field=models.CharField(default='something', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='chips',
            field=models.CharField(default='xz', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='choices',
            field=models.CharField(default='123', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.CharField(default='Moscow', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='country',
            field=models.CharField(default='Russia', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='name',
            field=models.CharField(default='Test-branch', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='timeout',
            field=models.CharField(default='123', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='work_hours',
            field=models.CharField(default='12-13:00', max_length=100),
            preserve_default=False,
        ),
    ]
