# Generated by Django 5.0.2 on 2024-02-27 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_remove_branch_chips_remove_branch_choices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches2', to='mainapp.branch')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Buisness_Type', to='mainapp.buisness_type')),
            ],
        ),
    ]
