# Generated by Django 5.0.2 on 2024-03-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_profile_password_changed_at_alter_employee_serviceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_usluga',
            field=models.BooleanField(default=False),
        ),
    ]
