# Generated by Django 5.0.2 on 2024-03-04 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_profile_first_filial_profile_first_sotrudnik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('timezone', models.CharField(max_length=128)),
                ('currency', models.CharField(max_length=128)),
                ('colour', models.CharField(max_length=128)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.profile')),
            ],
        ),
    ]
