# Generated by Django 5.0.2 on 2024-03-04 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_project_branch_project_employee_project_uslugi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_employee',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='project_employee',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project_uslugi',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project_uslugi',
            name='usluga',
        ),
        migrations.AddField(
            model_name='branch',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usluga',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.project'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Project_Branch',
        ),
        migrations.DeleteModel(
            name='Project_Employee',
        ),
        migrations.DeleteModel(
            name='Project_Uslugi',
        ),
    ]
