# Generated by Django 5.0.2 on 2024-03-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_widget_widgetimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='instagramlink',
            field=models.CharField(default='123', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widget',
            name='isinstagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='widget',
            name='istelegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='widget',
            name='isvk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='widget',
            name='iswhatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='widget',
            name='name',
            field=models.CharField(default='123', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widget',
            name='telegramlink',
            field=models.CharField(default='123', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widget',
            name='vklink',
            field=models.CharField(default='123', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widget',
            name='whatsapplink',
            field=models.CharField(default='123', max_length=100),
            preserve_default=False,
        ),
    ]
