# Generated by Django 5.0.2 on 2024-03-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_widget_instagramlink_widget_isinstagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='employees_id',
            field=models.CharField(default='1,2,3', max_length=1000),
            preserve_default=False,
        ),
    ]
