# Generated by Django 5.0.2 on 2024-03-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_branch_employees_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usluga',
            name='employees',
            field=models.CharField(default='', max_length=50),
        ),
    ]
