# Generated by Django 5.0.2 on 2024-03-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_widget_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
