# Generated by Django 5.0.2 on 2024-03-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_alter_profile_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='branches',
            field=models.CharField(default='1', max_length=10000),
            preserve_default=False,
        ),
    ]
