# Generated by Django 5.0.2 on 2024-03-29 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_widget_branches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='widget',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_widget_name'),
        ),
    ]
