# Generated by Django 5.0.1 on 2024-04-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_alter_widget_name_widget_unique_user_widget_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='daystime',
            field=models.JSONField(default=dict),
        ),
    ]
