# Generated by Django 5.0.1 on 2024-04-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_employee_daystime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='chilltime',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='days',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='timetable',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='worktime',
        ),
    ]
