# Generated by Django 5.0.1 on 2024-06-04 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_remove_employee_chilltime_remove_employee_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=128)),
                ('secondname', models.CharField(max_length=128)),
                ('mail', models.CharField(max_length=128)),
                ('img', models.ImageField(upload_to='clients/')),
                ('phone', models.CharField(max_length=128)),
                ('date', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=128)),
                ('data', models.CharField(max_length=256)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.project')),
                ('usluga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.usluga')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.client')),
            ],
        ),
    ]
