# Generated by Django 5.0.1 on 2024-06-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_client_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='buttonname',
            field=models.CharField(default='Play', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widget',
            name='hellomessage',
            field=models.CharField(default='Hello', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widget',
            name='telegramtoken',
            field=models.CharField(default='123', max_length=5000),
            preserve_default=False,
        ),
    ]
