# Generated by Django 5.0.1 on 2024-06-04 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_widget_buttonname_widget_hellomessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=2000)),
                ('status', models.BooleanField(default=False)),
                ('date', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.integration')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.widget')),
            ],
        ),
    ]
