# Generated by Django 5.0.6 on 2024-06-14 23:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0043_application_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
