# Generated by Django 5.0.6 on 2024-07-03 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0044_application_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
