# Generated by Django 5.0.6 on 2024-07-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0046_widgetload'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
