# Generated by Django 5.0.1 on 2024-07-07 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0047_application_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetload',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.project'),
            preserve_default=False,
        ),
    ]
